version: '3.8'

services:
  telemetry:
    build: .
    image: telemetry:dev
    ports:
      - '8000:8000'
    environment:
      - DATABASE_HOST=db
      - DATABASE_PASSWORD=password
      - DATABASE_USER=user
    entrypoint: ['docker-entrypoint.sh', 'uvicorn', '--host=0.0.0.0','main:app', '--reload']
    volumes:
      - ./src:/usr/src/app

  db:
    image: postgres:15-alpine
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=requests
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user

volumes:
  postgres:
